# Generated by Django 6.0.5 on 2026-05-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
